### PR TITLE
Update requirements-pure.txt

### PR DESCRIPTION
**Pull request by BKSteve**
List of items which did not get loaded when using SC as cross.

Search in code has them in `.lock` files only.

### CODE REVIEW

**Comment by miigotu** [comment]
You need to export them from poetry to do it correctly. Some requirements are for different versions of python, and will have the correct specifiers that way.

Then you need to split the compiled ones and the pure python ones.

`poetry export --without-hashes --with fast_parsing`

If it's ^= or ~= I hope their build system will let you leave it that way, it lets the latest patch or minor level for a given version of the dependency.

What you need to have installed is variable based on different environment factors. I'm surprised by the fanart one and some of the others honestly.

**Comment by BKSteve** [comment]
Well I installed poetry on the DSM (not loaded with SC) to run the `poetry export --without-hashes --with fast_parsing` and get this
```
bash-4.4$ /volume1/@appstore/sickchill/env/bin/poetry export --without-hashes --with fast_parsing

Poetry could not find a pyproject.toml file in /volume1/@appstore/sickchill/env or its parents
```
Searching in `/volume1/@appstore/sickchill/` no toml, looking in `/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill` nothing either.

here's the whole SC install log.
[sickchill.log](https://github.com/miigotu/spksrc/files/9591104/sickchill.log)

Also this is a build to align with the Python310 of SynoComm which loads a number of these itself.

**Comment by miigotu** [comment]
You don't need to export it on the syno, you export it on your PC after you clone the repo . It's the same requirements.txt regardless of the host.

**Comment by BKSteve** [comment]
OK, cross checked and put comments on those not in poetry list and the change of IMBbPY to cinemagoer
left other older ones not used hashed out at bottom

**Pull request closed without merging**
